eck-operator:
  managedNamespaces: ["elastic1", "elastic2", "elastic-monitoring"]
  createClusterScopedResources: true
  refs:
    enforceRBAC: true
  webhook:
    enabled: true
    namespaceSelector:
      matchExpressions:
        - key: "eck.k8s.elastic.co/tenant"
          operator: In
          values: ["elastic1", "elastic2", "elastic-monitoring"]
  softMultiTenancy:
    enabled: true