# ArgoCD Application to install the ECK operator via the wrapper chart (operator/eck-operator).
# The wrapper adds optional eck-trial-license Secret; set trialLicense.enabled in values to enable.
# Install this first; then deploy cluster Applications (single-node, multi-node, stack-monitoring).
# Set spec.source.repoURL and spec.source.targetRevision to your Git repo.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Javatar81/eck-examples
    path: operator/eck-operator
    targetRevision: main
    helm:
      releaseName: elastic-operator
      valueFiles:
        - values.yaml
        - values-rbac.yaml
      # To enable enterprise trial license, add:
      # By setting this to true you are expressing that you have accepted the Elastic EULA 
      #which can be found at https://www.elastic.co/eula.
      # values: |
      #   trialLicense:
      #     enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
