# ArgoCD Application: multi-node Elasticsearch + Kibana (2 ES nodes, 1 Kibana)
# Deploy after the eck-operator Application is synced.
# Set spec.source.repoURL to your Git repo URL and spec.source.targetRevision to branch/tag.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack-multi-node
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Javatar81/eck-examples
    path: clusters/eck-stack
    targetRevision: main
    destination:
      server: https://kubernetes.default.svc
      namespace: elastic
    helm:
      releaseName: eck-stack-multi-node
      valueFiles:
        - values.yaml
        - values-multi-node.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
